-- ============================================
-- Fix Order Number Generation with Postgres Sequence
-- Run this in Supabase SQL Editor
-- ============================================

-- PROBLEM: Order number generation is causing duplicate key errors
-- SOLUTION: Use a Postgres SEQUENCE for atomic, concurrent-safe generation

-- ============================================
-- 1. CREATE SEQUENCE
-- ============================================

CREATE SEQUENCE IF NOT EXISTS orders_order_number_seq;

-- Initialize sequence to be higher than any existing order numbers
DO $$
DECLARE
  max_num INT;
BEGIN
  SELECT COALESCE(MAX(CAST(SPLIT_PART(order_number, '-', 3) AS INT)), 0) + 1
  INTO max_num
  FROM orders
  WHERE order_number LIKE 'SC-%-_____';

  IF max_num > 1 THEN
    PERFORM setval('orders_order_number_seq', max_num, false);
  END IF;
END $$;

-- ============================================
-- 2. DROP THE OLD TRIGGER (if exists)
-- ============================================

DROP TRIGGER IF EXISTS set_order_number ON orders;
DROP FUNCTION IF EXISTS generate_order_number();

-- ============================================
-- 3. CREATE NEW FUNCTION FOR DEFAULT VALUE
-- ============================================

-- We need a function because DEFAULT can't use EXTRACT directly with concatenation
CREATE OR REPLACE FUNCTION generate_order_number_default()
RETURNS TEXT AS $$
BEGIN
  RETURN 'SC-' || EXTRACT(YEAR FROM now())::text || '-' ||
         LPAD(nextval('orders_order_number_seq')::text, 5, '0');
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 4. SET DEFAULT ON order_number COLUMN
-- ============================================

ALTER TABLE orders
ALTER COLUMN order_number SET DEFAULT generate_order_number_default();

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
--
-- After running this:
-- 1. Order numbers will be auto-generated by Postgres
-- 2. Format: SC-2024-00001, SC-2024-00002, etc.
-- 3. No duplicate key errors will occur
-- 4. App code should NOT pass order_number on insert
-- ============================================
